### ISSUE TITLE
Event.StopPropagation

### ISSUE THREAD

**Issue by mavatika** [partyka1/vue-material-design-ripple#2]
I'm currently using vue-material-design-ripple and it works great, I only found a bug-non-bug, because I have nested items which have the v-ripple directive on them and I noticed that if I click on a child element, it also creates the ripple effect on the parent and not only on the clicked children.
I tried by modifing the library locally and it just needs to add "e.stopPropagation();" on line 196 (inside function l, right after "n = e.currentTarget;") to make it works perfectly. I was wondering if it's possible to add that line of code to make this library the best and the easiest to use for Vue!

**Comment by kepi0809** [comment]
why don't you open a PR? Maybe that would be ignored too if the creator ignored this issue but maybe not ;)

**Comment by partyka1** [comment]
@mavatika send PR please! from your description you have clear solution in mind
