### ISSUE TITLE
11 dependencies?

### ISSUE THREAD

**Issue by AbrahamBrookes** [partyka1/vue-material-design-ripple#7]
Your front page says no dependencies, I installed via yarn and I get 11 new dependencies:

```
success Saved 11 new dependencies.
info Direct dependencies
└─ vue-material-design-ripple@1.0.0
info All dependencies
├─ awesome-typescript-loader@5.2.1
├─ d@1.0.1
├─ es5-ext@0.10.53
├─ es6-iterator@2.0.3
├─ ext@1.4.0
├─ log-symbols@2.2.0
├─ loglevelnext@1.0.5
├─ next-tick@1.0.0
├─ type@1.2.0
├─ typescript@3.9.5
└─ vue-material-design-ripple@1.0.0
```

**Comment by partyka1** [comment]
you can delete these just add your own scss/es6 processors.

**Comment by partyka1** [comment]
this package is built with mind that it probably will be used with webpack/typescript/scss processor already in place. maybe confusion as to "no dependencies" comes as it only has dev/build dependencies, but no actual runtime dependencies/libraries/ui frameworks beside vue it requires/ if you have good build tool in place with tree shaking support it should drop any unnecessary dev libs from your production build

**Comment by partyka1** [comment]
if you have an idea how to make the lib better im welcome to discussion and PRs

**Comment by partyka1** [comment]
i wanted to make sure, but `npm install` of this package will bundle you to your app, distribution version of the lib so you won't get any of the deps needed for development and build. you can check the build code at https://raw.githubusercontent.com/partyka1/vue-material-design-ripple/master/dist/vue-material-design-ripple.js
